import { useEffect, useState, useCallback } from "react";
import { AdminLayout } from "@/components/admin/AdminLayout";
import { DataTable } from "@/components/admin/DataTable";
import { StatusBadge } from "@/components/admin/StatusBadge";
import { api, ReportLog, PaginatedResponse } from "@/lib/api";
import { Button } from "@/components/ui/button";
import { Download } from "lucide-react";
import { exportToCSV } from "@/lib/csv";
import { toast } from "sonner";

export default function ReportLogPage() {
  const [data, setData] = useState<PaginatedResponse<ReportLog> | null>(null);
  const [page, setPage] = useState(1);
  const [statusFilter, setStatusFilter] = useState("");
  const [dateFrom, setDateFrom] = useState<string>();
  const [dateTo, setDateTo] = useState<string>();

  const fetchData = useCallback(() => {
    api.getReportLog({ page, per_page: 10, status: statusFilter || undefined, date_from: dateFrom, date_to: dateTo }).then(setData);
  }, [page, statusFilter, dateFrom, dateTo]);

  useEffect(() => { fetchData(); }, [fetchData]);

  const handleExport = () => {
    if (!data) return;
    exportToCSV(data.data, [
      { key: "id", label: "ID" }, { key: "report_type", label: "Report" },
      { key: "format", label: "Format" }, { key: "status", label: "Status" },
      { key: "file_size", label: "Size" }, { key: "created_at", label: "Generated" },
    ], "report_log");
    toast.success("CSV exported");
  };

  if (!data) return <AdminLayout><div className="flex items-center justify-center h-64"><div className="h-8 w-8 rounded-full border-2 border-primary border-t-transparent animate-spin" /></div></AdminLayout>;

  return (
    <AdminLayout>
      <div className="page-header">
        <h1 className="page-title">Report Log</h1>
        <p className="page-description">{data.total} reports generated</p>
      </div>
      <DataTable
        columns={[
          { key: "id", label: "ID" },
          { key: "report_type", label: "Report Type", render: (r) => <span className="font-medium">{r.report_type}</span> },
          { key: "generated_by", label: "Generated By" },
          { key: "format", label: "Format", render: (r) => (
            <span className={`text-xs font-semibold px-2 py-0.5 rounded-full ${r.format === 'CSV' ? 'bg-success/10 text-success' : 'bg-info/10 text-info'}`}>
              {r.format}
            </span>
          )},
          { key: "file_size", label: "Size" },
          { key: "status", label: "Status", render: (r) => <StatusBadge status={r.status} /> },
          { key: "created_at", label: "Generated At", render: (r) => (
            <span className="text-xs">{new Date(r.created_at).toLocaleString('en-IN', { day: 'numeric', month: 'short', hour: '2-digit', minute: '2-digit' })}</span>
          )},
          { key: "actions", label: "", render: (r) => r.status === 'completed' ? (
            <Button variant="ghost" size="icon" className="h-7 w-7"><Download className="h-4 w-4" /></Button>
          ) : null },
        ]}
        data={data.data}
        total={data.total}
        page={data.page}
        perPage={data.per_page}
        totalPages={data.total_pages}
        onPageChange={setPage}
        onExport={handleExport}
        onFilterChange={(key, val) => { if (key === "status") { setStatusFilter(val); setPage(1); } }}
        onDateRangeChange={(f, t) => { setDateFrom(f); setDateTo(t); setPage(1); }}
        filters={[{ key: "status", label: "Status", options: [{ value: "completed", label: "Completed" }, { value: "failed", label: "Failed" }, { value: "processing", label: "Processing" }] }]}
      />
    </AdminLayout>
  );
}
